### ISSUE TITLE
Invitation

### ISSUE THREAD

**Issue by tonysamperi** [formidablae/formidablae#2]
ciao, scusa se faccio questa cosa bruttissima.
Ho visto che mi hai invitato all'organizzazione "informatici di Bergamo".
Non sono riuscito a ricollegare chi sei...comunque sono entrato anche nel gruppo Telegram, se mai scrivimi lì se vuoi!

Ciao!

**Comment by formidablae** [comment]
Ciao
non ci conosciamo personalmente ahah.
Sono il fondatore del canale https://t.me/informatici_bergamo . Oltre al
canale ci stiamo muovendo per avere anche una sorta di rete locale
bergamasca su github.
Così per sapere che progetti (informatici) ci sono nei dintorni, chi ha
bisogno di collaboratori, di aiuto, conoscere le persone ecc...
Ti scrivo anche su telegram.
A presto :)
