### ISSUE TITLE
"server" is misspelled

### ISSUE THREAD

**Issue by almostengr** [formidablae/formidablae#46]
In the badge mentioned below, the word "Server" is misspelled. It is missing the first "R"

https://github.com/formidablae/formidablae/blob/c4b347bca89cf8e24ffdd34a23b09442f42fb0b1/README.md?plain=1#L128

**Comment by formidablae** [comment]
Hello @almostengr, thank you for pointing it out. Your contribution is really appreciated.
The type has now been fixed.
Looking forward to your next contribution :)
